variable = ""
variable += "<!DOCTYPE html>\n"
variable += "<!--\n"
variable += "To change this license header, choose License Headers in Project Properties.\n"
variable += "To change this template file, choose Tools | Templates\n"
variable += "and open the template in the editor.\n"
variable += "-->\n"
variable += "<html>\n"
variable += "    <head>\n"
variable += "        <meta charset=\"UTF-8\">\n"
variable += "        <title></title>\n"
variable += "    </head>\n"
variable += "    <body>\n"
variable += "        <table border=\"1\">\n"
variable += "            <thead>\n"
variable += "                <tr>\n"
variable += "                    <th>id</th>\n"
variable += "                    <th>Tipo</th>\n"
variable += "                    <th>Cant.</th>\n"
variable += "                    <th>Div. 1</th>\n"
variable += "                    <th>Cant.</th>\n"
variable += "                    <th>Div. 2</th>\n"
variable += "                    <th>Cant.</th>\n"
variable += "                </tr>\n"
variable += "            </thead>\n"
variable += "            <tbody>\n"
variable += "                <tr>\n"
variable += "                    <td>1</td>\n"
variable += "                    <td>unknown</td>\n"
variable += "                    <td>941</td>\n"
variable += "                    <td>TLS</td>\n"
variable += "                    <td>1</td>\n"
variable += "                    <td>HOMOGENEO</td>\n"
variable += "                    <td>940</td>\n"
variable += "                </tr>\n"
variable += "            </tbody>\n"
variable += "        </table>\n"
variable += "    </body>\n"
variable += "</html>\n"
print(variable
)
fin = input()